### ISSUE TITLE
Failed tests are registered as successful

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/CITA#20] opened 2023-07-16 09:02 UTC
If a test follows the procedure and creates a file named [$CITA_LOG],'.err' and returns a non-empty result, the executor still registers it as successful.

**Comment by mbaas2** [comment] 2023-07-31 15:34
- the reason your test had double results was that your code wrote a file to indicate failure and then the fn ended. The "expected behaviour" would be to `⎕OFF ` when a test has ended (and thats what the "support" functions `LogStatus`, `Fail`, `Success` etc. do). 
- the fact that the interpreter was running after the test had ended led to the mistake of creating the "ok" status file - I'm planning to fix this by simply doing ⎕OFF if a status file exists and otherwise creating one with .err extension to record that the test did not create a statusfile.

**Comment by mkromberg** [comment] 2023-07-31 15:47
I think your plan is a good one - it should not be necessary for the "user code" to also do a ⎕OFF - it should be up to the framework to decide how to end the session in good order.

**Comment by mbaas2** [comment] 2023-11-03 10:54
This has been fixed meanwhile ( 5d5c10235e278775deb7ae0e1d7c5597ebb81ea3 ). I merged the "devt" branch yesterday.

**Closed by mbaas2** 2023-11-03 10:54 UTC
